export const locations = [
  { label: "Delhi", slug: "screw-compressor-in-delhi" },
  { label: "Gurgaon", slug: "screw-compressor-in-gurgaon" },
  { label: "Noida", slug: "screw-compressor-in-noida" },
  { label: "Greater Noida", slug: "screw-compressor-in-greater-noida" },
  { label: "Ghaziabad", slug: "screw-compressor-in-ghaziabad" },
  { label: "Faridabad", slug: "screw-compressor-in-faridabad" },
  { label: "Manesar", slug: "screw-compressor-in-manesar" },
  { label: "Sonipat", slug: "screw-compressor-in-sonipat" },
  { label: "Panipat", slug: "screw-compressor-in-panipat" },
  { label: "Meerut", slug: "screw-compressor-in-meerut" },
  { label: "Bhiwadi", slug: "screw-compressor-in-bhiwadi" },
  { label: "Bahadurgarh", slug: "screw-compressor-in-bahadurgarh" },
  { label: "Bawal", slug: "screw-compressor-in-bawal" },
  { label: "Sikandrabad", slug: "screw-compressor-in-sikandrabad" },
  { label: "Loni", slug: "screw-compressor-in-loni" },
  { label: "Badarpur", slug: "screw-compressor-in-badarpur" },
  { label: "Rohtak", slug: "screw-compressor-in-rohtak" },
  { label: "Moradabad", slug: "screw-compressor-in-moradabad" },
  { label: "Haridwar", slug: "screw-compressor-in-haridwar" },
  { label: "Roorkee", slug: "screw-compressor-in-roorkee" },
  { label: "Saharanpur", slug: "screw-compressor-in-saharanpur" },
  { label: "Bareilly", slug: "screw-compressor-in-bareilly" },
  { label: "Jhajjar", slug: "screw-compressor-in-jhajjar" },
  { label: "Bilaspur", slug: "screw-compressor-in-bilaspur" },
  { label: "Jammu", slug: "screw-compressor-in-jammu" },
  { label: "Pulwama", slug: "screw-compressor-in-pulwama" }
];